version: "3"

services:
  app:
    container_name: express-mongo
    restart: always
    build: ./server
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://localhost:3000
      - SPOTIFY_PUBLIC=1bda6c1687914623bab9fbee30595f52
      - SPOTIFY_SECRET=2508ed3146da425f9c3494a77ce994a1
      - CORS=http://localhost:3000,http://localhost:3001
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  web:
    container_name: web
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://localhost:8080
