name: Server CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Run Buildx
        working-directory: ./server/
        run: |
          ls && docker buildx build \
            --platform linux/386,linux/amd64,linux/arm64 \
            --output "type=image" --push \
            --tag yooooomi/your_spotify_server ./
